
#-----------------------------------------------------------------------

APP       := Test
TARGET    := RedisDemo
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= --json

INCLUDE += -I../../redis
#-----------------------------------------------------------------------
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
